// src/components/HomePage.vue
<template>
  <div class="hello">
    <h1>Welcome {{ fname }} {{lname}}!</h1>
    <p>What is your name?</p>
    <form>
      <label for="fname">First Name</label>
      <input type="text" id="fname" v-model="fname"/><br>

      <label for="lname">Last Name</label>
      <input type="text" id="lname" v-model="lname"/><br>

      <input type="radio" name="pic" id="ocean" value="ocean" v-model="pic"/>
      <label for="ocean">Ocean</label>
      <input type="radio" name="pic" id="mountain" value="mountain" v-model="pic"/>
      <label for="mountain">Mountain</label>
      
      <div v-if="pic == 'mountain'">
        <img src="../assets/mountain.jpg" alt="mountain" id="mountainImg">
      </div>
      <div v-else-if="pic == 'ocean'">
        <img src="../assets/ocean.jpg" alt="ocean" id="oceanImg">
      </div>
    </form>
  </div>
</template>

<script>
export default {
  data(){
    return{
      name: 'HomePage',
      fname: '',
      lname: '',
      pic: ''
    }
  }
}
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
h3 {
  margin: 40px 0 0;
}
ul {
  list-style-type: none;
  padding: 0;
}
li {
  display: inline-block;
  margin: 0 10px;
}
a {
  color: #42b983;
}
label, input{
  margin-top: 1vw;
  margin-bottom: 1vw;
}

img{
  display: inline-block;
  width: 30%;
}
</style>

// src/components/HomePage.jsx
import styled from 'styled-components';
import { useState } from 'react';
import mountain from '../assets/mountain.jpg';
import ocean from '../assets/ocean.jpg';


export default function HomePage(){
  const [pic, setPic] = useState();
  const [nm, setName] = useState({first: '', last: ''});
  const handleChange = (e) => {
      const { name, value } = e.target;
      setName(nm => ({
          ...nm,
          [name]: value
      }));
  }
  return(
    <div>
      <h2 id="title" className="pageTitle">Homepage</h2>

      <form>
        
        <h3 className='container'>{nm.first!=="" || nm.last!=="" ? "Welcome, " : ''}{nm.first + " " + nm.last}</h3>
        
        <Group>
          <label for="first">First Name: </label>
          <input type="text" id="first" name="first" onChange={(e) => handleChange(e)}/>
        </Group>

        <Group>
          <label for="lname">Last Name: </label>
          <input type="text" id="last" name="last" onChange={(e) => handleChange(e)} />
        </Group>

        <Group >
          <RadioButton type="radio" name="pic" id="ocean" value="ocean" onChange={() => setPic(ocean)}/>
          <label for="ocean">Ocean</label>

          <RadioButton type="radio" name="pic" id="mountain" value="mountain" onChange={() => setPic(mountain)}/>
          <label for="mountain">Mountain</label>
        </Group>

        <div className="container">
          <ResultPic src={pic}></ResultPic>
        </div>
      
      </form>

    </div>
  )
}

const Group = styled.label`
  font-size: 1.2em;
  display: flex;
  flex-direction: row;
  margin: 2vw;
  align-items: center;
  justify-content: center;
`;

const RadioButton = styled.input`
  width: 2em;
  height: 1.7em;
`;

const ResultPic = styled.img`
  width: 50%;
  margin-bottom: 5em
`;
